### PR TITLE
minSdkVersion 21

### PR DESCRIPTION
**Pull request by hobbit-frodo**
may we lower minSDK to 21? many thanks!

### CODE REVIEW

**Comment by i-schuetz** [comment]
Does it build and run on with this min api?

**Comment by hobbit-frodo** [comment]
yes, all the changes that I've done have been build and tested on my device with minSDK=21,many thanks

**Comment by i-schuetz** [comment]
This is incompatible with https://github.com/Co-Epi/app-android/pull/21, where we will have to request multiple permissions (supported only with 26 minSDK). 

Can you please investigate that? 

If Api 21 introduces too much inconveniences, we can't use it (for now, at least), as it would slow down the MVP.

**Comment by mmathieum** [comment]
#21 uses ContextCompat which is backward compatible with API Level 21

**Comment by i-schuetz** [comment]
Ok, don't remember well what's covered by the support lib. If the lower API doesn't cause issues, we're good.

**Pull request merged**
